package com.shoes.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CartItemsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartItemsAllPropertiesEquals(CartItems expected, CartItems actual) {
        assertCartItemsAutoGeneratedPropertiesEquals(expected, actual);
        assertCartItemsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartItemsAllUpdatablePropertiesEquals(CartItems expected, CartItems actual) {
        assertCartItemsUpdatableFieldsEquals(expected, actual);
        assertCartItemsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartItemsAutoGeneratedPropertiesEquals(CartItems expected, CartItems actual) {
        assertThat(expected)
            .as("Verify CartItems auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartItemsUpdatableFieldsEquals(CartItems expected, CartItems actual) {
        assertThat(expected)
            .as("Verify CartItems relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartItemsUpdatableRelationshipsEquals(CartItems expected, CartItems actual) {
        assertThat(expected)
            .as("Verify CartItems relationships")
            .satisfies(e -> assertThat(e.getCart()).as("check cart").isEqualTo(actual.getCart()))
            .satisfies(e -> assertThat(e.getColors()).as("check colors").isEqualTo(actual.getColors()))
            .satisfies(e -> assertThat(e.getShoeVariants()).as("check shoeVariants").isEqualTo(actual.getShoeVariants()))
            .satisfies(e -> assertThat(e.getSizes()).as("check sizes").isEqualTo(actual.getSizes()));
    }
}
