package com.shoes.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WishListItemsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListItemsAllPropertiesEquals(WishListItems expected, WishListItems actual) {
        assertWishListItemsAutoGeneratedPropertiesEquals(expected, actual);
        assertWishListItemsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListItemsAllUpdatablePropertiesEquals(WishListItems expected, WishListItems actual) {
        assertWishListItemsUpdatableFieldsEquals(expected, actual);
        assertWishListItemsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListItemsAutoGeneratedPropertiesEquals(WishListItems expected, WishListItems actual) {
        assertThat(expected)
            .as("Verify WishListItems auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListItemsUpdatableFieldsEquals(WishListItems expected, WishListItems actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListItemsUpdatableRelationshipsEquals(WishListItems expected, WishListItems actual) {
        assertThat(expected)
            .as("Verify WishListItems relationships")
            .satisfies(e -> assertThat(e.getWishList()).as("check wishList").isEqualTo(actual.getWishList()));
    }
}
